"use strict";

/**
 * kits.js — Definición de Kits para Minecraft 1.8.9
 * =================================================
 * Cada kit define un estilo de juego, ítems/reglas sugeridas y sus nerfeos personalizados.
 */

const KITS = [
  {
    id: 'melee_clasico',
    nombre: 'Full Diamante (Melee Clásico)',
    icon: '⚔️',
    color: '#38bdf8',
    descripcion: 'Armadura de Diamante completa y Espada Sharp II. Curación limitada a 4 Manzanas Doradas normales.',
    items: ['Diamante Completo', 'Espada Sharp II', '4 Manzanas Doradas', 'Speed II'],
    nerfs: [
      {
        id: 'downgrade_pechera',
        categoria: 'Defensa',
        categoriaKey: 'defensa',
        categoriaIcon: '🛡️',
        color: '#60a5fa',
        nombre: 'Armadura de Cuero',
        descripcion: 'Todo su diamante se reemplaza por armadura de cuero básica.',
        impacto: 'Se vuelve extremadamente fácil de matar.',
        severity: 3,
      },
      {
        id: 'downgrade_encantamientos',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '👁️‍🌫️',
        color: '#f472b6',
        nombre: 'Ceguera Temporal',
        descripcion: 'Juega con el efecto de Ceguera (Blindness) durante la pelea.',
        impacto: 'Dificultad de visión severa.',
        severity: 3,
      },
      {
        id: 'arma_hierro',
        categoria: 'Ataque',
        categoriaKey: 'ataque',
        categoriaIcon: '🪵',
        color: '#f87171',
        nombre: 'Espada de Madera',
        descripcion: 'Reemplaza su espada Sharp II por una espada de madera.',
        impacto: 'Daño de golpe drásticamente reducido.',
        severity: 3,
      },
      {
        id: 'sin_arco',
        categoria: 'Defensa',
        categoriaKey: 'defensa',
        categoriaIcon: '👙',
        color: '#ef4444',
        nombre: 'Sin Armadura',
        descripcion: 'Entra a la arena completamente desprotegido.',
        impacto: 'El oponente lo eliminará de 2 o 3 golpes.',
        severity: 3,
      },
      {
        id: 'sin_gapples',
        categoria: 'Sustain',
        categoriaKey: 'sustain',
        categoriaIcon: '❌',
        color: '#4ade80',
        nombre: 'Sin Curación',
        descripcion: 'Se le quitan las 4 manzanas doradas (no puede curarse).',
        impacto: 'Cualquier daño recibido será permanente.',
        severity: 3,
      },
      {
        id: 'sin_mechero',
        categoria: 'Sustain',
        categoriaKey: 'sustain',
        categoriaIcon: '💔',
        color: '#f59e0b',
        nombre: 'Mitad de Vida',
        descripcion: 'Comienza el duelo con solo 5 corazones (50% de vida máxima).',
        impacto: 'Empieza en desventaja crítica de HP.',
        severity: 3,
      },
      {
        id: 'sin_cana',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '🐢',
        color: '#6b7280',
        nombre: 'Lentitud III',
        descripcion: 'Movimiento drásticamente reducido con Lentitud III.',
        impacto: 'Es casi imposible esquivar o perseguir.',
        severity: 3,
      },
      {
        id: 'weakness_i',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '🥀',
        color: '#a855f7',
        nombre: 'Debilidad II',
        descripcion: 'Reduce severamente el daño que inflige por golpe.',
        impacto: 'Necesitará conectar docenas de golpes para ganar.',
        severity: 3,
      },
      {
        id: 'slowness_i',
        categoria: 'Ataque',
        categoriaKey: 'ataque',
        categoriaIcon: '👊',
        color: '#22c55e',
        nombre: 'Solo Puños',
        descripcion: 'Fuerza al experto a pelear con las manos vacías.',
        impacto: 'Sin espada. Solo daño base de puño.',
        severity: 3,
      }
    ]
  },
  {
    id: 'glass_cannon',
    nombre: 'Glass Cannon (Daño Extremo)',
    icon: '⚡',
    color: '#f59e0b',
    descripcion: 'Armadura de Diamante sin encantar y Espada Sharp V. Combates brutales que terminan en segundos.',
    items: ['Diamante Sin Encantar', 'Espada Sharp V', 'Sin Curación'],
    nerfs: [
      {
        id: 'downgrade_pechera',
        categoria: 'Defensa',
        categoriaKey: 'defensa',
        categoriaIcon: '🛡️',
        color: '#60a5fa',
        nombre: 'Pechera de Cuero',
        descripcion: 'Cambia su pechera por una de cuero (se vuelve extremadamente frágil).',
        impacto: 'Muere aún más rápido.',
        severity: 3,
      },
      {
        id: 'downgrade_encantamientos',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '👁️‍🌫️',
        color: '#f472b6',
        nombre: 'Ceguera Temporal',
        descripcion: 'Juega con el efecto de ceguera constante.',
        impacto: 'Imposible ver la dirección del oponente.',
        severity: 3,
      },
      {
        id: 'arma_hierro',
        categoria: 'Ataque',
        categoriaKey: 'ataque',
        categoriaIcon: '🪵',
        color: '#f87171',
        nombre: 'Espada de Oro',
        descripcion: 'Reemplaza su espada Sharp V por una de oro sin encantar.',
        impacto: 'Pierde su principal ventaja de daño.',
        severity: 3,
      },
      {
        id: 'sin_arco',
        categoria: 'Defensa',
        categoriaKey: 'defensa',
        categoriaIcon: '👙',
        color: '#ef4444',
        nombre: 'Sin Armadura',
        descripcion: 'Entra a pelear sin ninguna pieza de armadura.',
        impacto: 'Cualquier golpe del oponente lo liquidará.',
        severity: 3,
      },
      {
        id: 'sin_gapples',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '❌',
        color: '#4ade80',
        nombre: 'Fatiga de Ataque',
        descripcion: 'Se le aplica fatiga para reducir su velocidad de clicks.',
        impacto: 'Dificulta hacer combos rápidos.',
        severity: 2,
      },
      {
        id: 'sin_mechero',
        categoria: 'Sustain',
        categoriaKey: 'sustain',
        categoriaIcon: '💔',
        color: '#f59e0b',
        nombre: 'Mitad de Vida',
        descripcion: 'Comienza el combate con solo 5 corazones.',
        impacto: 'Prácticamente muere de un solo golpe.',
        severity: 3,
      },
      {
        id: 'sin_cana',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '🐢',
        color: '#6b7280',
        nombre: 'Lentitud III',
        descripcion: 'Movimiento muy ralentizado.',
        impacto: 'No puede esquivar la ráfaga de golpes.',
        severity: 3,
      },
      {
        id: 'weakness_i',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '🥀',
        color: '#a855f7',
        nombre: 'Debilidad III',
        descripcion: 'Reduce su daño drásticamente para contrarrestar la Sharp V.',
        impacto: 'Su espada gigante ahora pega como madera.',
        severity: 3,
      },
      {
        id: 'slowness_i',
        categoria: 'Ataque',
        categoriaKey: 'ataque',
        categoriaIcon: '👊',
        color: '#22c55e',
        nombre: 'Solo Puños',
        descripcion: 'Se le quita la espada de alto daño, forzándole a usar las manos.',
        impacto: 'Pierde por completo el rol de Glass Cannon.',
        severity: 3,
      }
    ]
  },
  {
    id: 'combo_speed',
    nombre: 'Combo Speed (Velocidad)',
    icon: '⚡',
    color: '#a855f7',
    descripcion: 'Armadura Prot I y Espada Sharp III. Velocidad II constante y 0 curación.',
    items: ['Diamante Prot I', 'Espada Sharp III', 'Speed II', 'Sin Curación'],
    nerfs: [
      {
        id: 'downgrade_pechera',
        categoria: 'Defensa',
        categoriaKey: 'defensa',
        categoriaIcon: '🛡️',
        color: '#60a5fa',
        nombre: 'Armadura de Cuero',
        descripcion: 'Su armadura de protección I pasa a ser de cuero.',
        impacto: 'Recibe daño masivo por combo.',
        severity: 3,
      },
      {
        id: 'downgrade_encantamientos',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '👁️‍🌫️',
        color: '#f472b6',
        nombre: 'Ceguera Temporal',
        descripcion: 'Juega con el efecto de ceguera.',
        impacto: 'Dificultad crítica para orientarse a alta velocidad.',
        severity: 3,
      },
      {
        id: 'arma_hierro',
        categoria: 'Ataque',
        categoriaKey: 'ataque',
        categoriaIcon: '🪵',
        color: '#f87171',
        nombre: 'Espada de Madera',
        descripcion: 'Cambia su espada Sharp III por una de madera.',
        impacto: 'Su combo rápido no causará casi daño.',
        severity: 3,
      },
      {
        id: 'sin_arco',
        categoria: 'Defensa',
        categoriaKey: 'defensa',
        categoriaIcon: '👙',
        color: '#ef4444',
        nombre: 'Sin Armadura',
        descripcion: 'Pelea completamente sin protección.',
        impacto: 'Cualquier roce lo liquida.',
        severity: 3,
      },
      {
        id: 'sin_gapples',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '❌',
        color: '#4ade80',
        nombre: 'Sin Velocidad II',
        descripcion: 'Se le quita el efecto de Velocidad II.',
        impacto: 'Pierde su movilidad y ventaja técnica.',
        severity: 3,
      },
      {
        id: 'sin_mechero',
        categoria: 'Sustain',
        categoriaKey: 'sustain',
        categoriaIcon: '💔',
        color: '#f59e0b',
        nombre: 'Mitad de Vida',
        descripcion: 'Comienza con 5 corazones.',
        impacto: 'Una ráfaga de golpes lo elimina al instante.',
        severity: 3,
      },
      {
        id: 'sin_cana',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '🐢',
        color: '#6b7280',
        nombre: 'Lentitud IV',
        descripcion: 'Se le aplica Lentitud IV para anular su velocidad.',
        impacto: 'Se vuelve una estatua viviente.',
        severity: 3,
      },
      {
        id: 'weakness_i',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '🥀',
        color: '#a855f7',
        nombre: 'Debilidad II',
        descripcion: 'Reduce fuertemente el daño por golpe.',
        impacto: 'Sus ataques veloces causan daño mínimo.',
        severity: 3,
      },
      {
        id: 'slowness_i',
        categoria: 'Ataque',
        categoriaKey: 'ataque',
        categoriaIcon: '👊',
        color: '#22c55e',
        nombre: 'Solo Puños',
        descripcion: 'Fuerza al experto a no usar su espada Sharp III.',
        impacto: 'Pelea solo con puños a alta velocidad.',
        severity: 3,
      }
    ]
  },
  {
    id: 'nodebuff_express',
    nombre: 'Nodebuff Express',
    icon: '🧪',
    color: '#ec4899',
    descripcion: 'Combate de pociones clásico pero rápido. 5 pociones de curación y Speed II.',
    items: ['Diamante Completo', 'Espada Sharp IV', '5 Pociones de Vida II', 'Speed II'],
    nerfs: [
      {
        id: 'downgrade_pechera',
        categoria: 'Defensa',
        categoriaKey: 'defensa',
        categoriaIcon: '🛡️',
        color: '#60a5fa',
        nombre: 'Armadura de Cuero',
        descripcion: 'Reemplaza su diamante por armadura de cuero completa.',
        impacto: 'Sus pociones se consumirán mucho más rápido.',
        severity: 3,
      },
      {
        id: 'downgrade_encantamientos',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '👁️‍🌫️',
        color: '#f472b6',
        nombre: 'Ceguera Temporal',
        descripcion: 'Juega con el efecto de ceguera.',
        impacto: 'Dificultad extrema para apuntar las pociones.',
        severity: 3,
      },
      {
        id: 'arma_hierro',
        categoria: 'Ataque',
        categoriaKey: 'ataque',
        categoriaIcon: '🪵',
        color: '#f87171',
        nombre: 'Espada de Hierro',
        descripcion: 'Reemplaza la espada Sharp IV de diamante por una de hierro.',
        impacto: 'Menor daño por segundo en combate melee.',
        severity: 3,
      },
      {
        id: 'sin_arco',
        categoria: 'Defensa',
        categoriaKey: 'defensa',
        categoriaIcon: '👙',
        color: '#ef4444',
        nombre: 'Sin Armadura',
        descripcion: 'Entra a combatir sin protección.',
        impacto: 'Obligado a lanzar pociones constantemente para sobrevivir.',
        severity: 3,
      },
      {
        id: 'sin_gapples',
        categoria: 'Sustain',
        categoriaKey: 'sustain',
        categoriaIcon: '❌',
        color: '#4ade80',
        nombre: 'Sin Pociones',
        descripcion: 'Se le quitan todas las pociones de curación (0 pociones).',
        impacto: 'Sin capacidad de regenerar vida en combate.',
        severity: 3,
      },
      {
        id: 'sin_mechero',
        categoria: 'Sustain',
        categoriaKey: 'sustain',
        categoriaIcon: '💔',
        color: '#f59e0b',
        nombre: 'Mitad de Vida',
        descripcion: 'Empieza con 5 corazones.',
        impacto: 'Muy vulnerable a morir antes de curarse.',
        severity: 3,
      },
      {
        id: 'sin_cana',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '🐢',
        color: '#6b7280',
        nombre: 'Lentitud III',
        descripcion: 'Movimiento muy lento.',
        impacto: 'Dificulta esquivar combos del oponente.',
        severity: 3,
      },
      {
        id: 'weakness_i',
        categoria: 'Estado',
        categoriaKey: 'estado',
        categoriaIcon: '🥀',
        color: '#a855f7',
        nombre: 'Debilidad II',
        descripcion: 'Reduce su fuerza de ataque notablemente.',
        impacto: 'Pega mucho menos que el oponente.',
        severity: 3,
      },
      {
        id: 'slowness_i',
        categoria: 'Ataque',
        categoriaKey: 'ataque',
        categoriaIcon: '👊',
        color: '#22c55e',
        nombre: 'Solo Puños',
        descripcion: 'Pelea solo a puño limpio.',
        impacto: 'Sin espada. Solo pociones y sus puños.',
        severity: 3,
      }
    ]
  }
];

function getRandomKit() {
  return KITS[Math.floor(Math.random() * KITS.length)];
}

function getKitById(id) {
  return KITS.find(k => k.id === id) || KITS[0];
}

module.exports = { KITS, getRandomKit, getKitById };
